/*
 * Created on 21 giu 2016 ( Time 11:50:55 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package it.mesis.avis.service.mapping;

import it.mesis.avis.service.mapping.AbstractServiceMapper;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;

/**
 * Mapping between entity beans and display beans.
 */
public class OrderServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public OrderServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);	//loose è "a maglie larghe"
	}

	/**
	 * Mapping from 'orderEntity' to 'Audit'
	 * @param auditEntity
	 */
	public OrderDto mapOrderToOrderDto(Order orderEntity) {
		if(orderEntity == null) {
			return null;
		}

		//--- Generic mapping 
		OrderDto orderDto = map(orderEntity, OrderDto.class);

		return orderDto;
	}
	
	/**
	 * Mapping from 'orderDto' to 'orderEntity'
	 * @param audit
	 * @param auditEntity
	 */
	public void mapOrderDtoToOrderEntity(OrderDto orderDto, Order orderEntity) {
		if(orderDto == null) {
			return;
		}
		//--- Generic mapping 
		map(orderDto, orderEntity);
	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}