/*
 * Created on 21 giu 2016 ( Time 11:51:50 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package it.mesis.avis.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Agenda implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Date dataorapren;
    @NotNull
    private Integer idmacchina;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String notapren;

    @Size( max = 50 )
    private String codinternodonat;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setDataorapren( Date dataorapren ) {
        this.dataorapren = dataorapren ;
    }

    public Date getDataorapren() {
        return this.dataorapren;
    }

    public void setIdmacchina( Integer idmacchina ) {
        this.idmacchina = idmacchina ;
    }

    public Integer getIdmacchina() {
        return this.idmacchina;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNotapren( String notapren ) {
        this.notapren = notapren;
    }
    public String getNotapren() {
        return this.notapren;
    }

    public void setCodinternodonat( String codinternodonat ) {
        this.codinternodonat = codinternodonat;
    }
    public String getCodinternodonat() {
        return this.codinternodonat;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(dataorapren);
        sb.append("|");
        sb.append(notapren);
        sb.append("|");
        sb.append(idmacchina);
        sb.append("|");
        sb.append(codinternodonat);
        return sb.toString(); 
    } 


}
