/*
 * Created on 21 giu 2016 ( Time 11:51:50 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package it.mesis.avis.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Audit implements Serializable {

    private static final long serialVersionUID = 1L;
    
    
	public Audit() {
	}
    
	public Audit(String ssoId, String state, Date created) {
		super();
		this.ssoId = ssoId;
		this.created = created;
		this.state = state;
	}

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Date created;

    @NotNull
    @Size( min = 1, max = 30 )
    private String ssoId;

    @NotNull
    @Size( min = 1, max = 250 )
    private String state;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCreated( Date created ) {
        this.created = created;
    }
    public Date getCreated() {
        return this.created;
    }

    public void setSsoId( String ssoId ) {
        this.ssoId = ssoId;
    }
    public String getSsoId() {
        return this.ssoId;
    }

    public void setState( String state ) {
        this.state = state;
    }
    public String getState() {
        return this.state;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(created);
        sb.append("|");
        sb.append(ssoId);
        sb.append("|");
        sb.append(state);
        return sb.toString(); 
    } 


}
