/*
 * Created on 21 giu 2016 ( Time 11:51:51 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package it.mesis.avis.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Donatore implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 50 )
    private String codinternodonat;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer ab0;

    @NotNull
    private Integer aferesianno;

    @NotNull
    private Short aferesimultipla;

    @NotNull
    private Integer aferesipregres;

    @Size( max = 4 )
    private String allerg2al;

    @Size( max = 4 )
    private String allerg2dal;

    @Size( max = 4 )
    private String allergal;

    @Size( max = 4 )
    private String allergdal;

    @Size( max = 255 )
    private String altracarica;

    @NotNull
    private Integer bloccatoda;


    private Date cancelladefin;

    @NotNull
    private Short capofamiglia;

    @NotNull
    private Integer caricasociale;

    @Size( max = 20 )
    private String cellulare;

    @NotNull
    private Short cellulestamina;

    @Size( max = 6 )
    private String codcomunenasc;

    @NotNull
    private Integer codconvocazion;

    @Size( max = 50 )
    private String codicedonatore;

    @Size( max = 16 )
    private String codicefiscale;

    @Size( max = 10 )
    private String codicelogido;

    @Size( max = 20 )
    private String codicereg;

    @Size( max = 255 )
    private String cognomedasposat;

    @Size( max = 61 )
    private String cognomeenome;

    @NotNull
    private Short commissione1;

    @NotNull
    private Short commissione2;

    @NotNull
    private Short commissione3;

    @NotNull
    private Short commissione4;

    @NotNull
    private Short commissione5;

    @NotNull
    private Short commissione6;

    @NotNull
    private Short commissione7;

    @NotNull
    private Short commissione8;

    @NotNull
    private Short commissione9;

    @NotNull
    private Short consigplasmaf;

    @NotNull
    private Short convocato;


    private Date dataaltraben;


    private Date databenemerenz;


    private Date dataconvpren;


    private Date datacroceoro;


    private Date datadinascita;


    private Date datadistintivo;


    private Date datafinestato;


    private Date datagocciaarg;


    private Date datagocciabro;


    private Date datagocciaoro;


    private Date datainiziostato;


    private Date datamedargent;


    private Date datamedbronzo;


    private Date datamedoro;


    private Date datanuovaanagrafica;


    private Date datapremagg;


    private Date dataprimaiscr;


    private Date datarubinocoll;

    @Size( max = 20 )
    private String dettagliososp;

    @Size( max = 5 )
    private String domcap;

    @Size( max = 50 )
    private String domcitta;

    @Size( max = 80 )
    private String domindirizzo;

    @Size( max = 6 )
    private String domistat;

    @Size( max = 40 )
    private String domlocalita;

    @Size( max = 2 )
    private String domprov;


    private Short domresuguali;

    @Size( max = 20 )
    private String domtel;

    @NotNull
    private Integer donazanno;

    @NotNull
    private Integer donazionipregr;

    @NotNull
    private Short donazionipregrdopo2004;

    @NotNull
    private Short doppiapltaf;

    @Size( max = 255 )
    private String email;

    @NotNull
    private Short eritroplasma;

    @NotNull
    private Short eritroplt;

    @Size( max = 255 )
    private String fermoposta;

    @NotNull
    private Short flagallergia;

    @NotNull
    private Short flagaltrabene;

    @NotNull
    private Short flagbenemerenz;

    @NotNull
    private Short flagcroceoro;

    @NotNull
    private Short flagdistintivo;

    @NotNull
    private Short flaggocciaarg;

    @NotNull
    private Short flaggocciabro;

    @NotNull
    private Short flaggocciaoro;

    @NotNull
    private Short flagmail;

    @NotNull
    private Short flagmedargent;

    @NotNull
    private Short flagmedbronzo;

    @NotNull
    private Short flagmedoro;

    @NotNull
    private Short flagpremagg;

    @NotNull
    private Short flagreperibile;

    @NotNull
    private Short flagrubinocoll;

    @NotNull
    private Short flagsms;

    @NotNull
    private Integer gruppoorganizz;

    @NotNull
    private Integer idoneita;

    @NotNull
    private Short importato;

    @NotNull
    private Short indicpiastrafer;

    @NotNull
    private Integer intervalloafeaf;

    @NotNull
    private Integer intervalloafesa;

    @NotNull
    private Integer intervallosalaf;

    @NotNull
    private Integer intervallosalsa;

    @NotNull
    private Short iscradmo;

    @NotNull
    private Short iscraido;

    @NotNull
    private Integer kell;

    @Size( max = 16 )
    private String lavcodice;

    @Size( max = 20 )
    private String lavtel;

    @NotNull
    private Short leggeprivacy;

    @NotNull
    private Short lettprimadonstampata;

    @NotNull
    private Short leucoaferesi;

    @NotNull
    private Short libero0;

    @NotNull
    private Short libero1;

    @NotNull
    private Short libero10;

    @NotNull
    private Short libero11;

    @NotNull
    private Short libero2;

    @NotNull
    private Short libero3;

    @NotNull
    private Short libero4;

    @NotNull
    private Short libero5;

    @NotNull
    private Short libero6;

    @NotNull
    private Short libero7;

    @NotNull
    private Short libero8;

    @NotNull
    private Short libero9;

    @Size( max = 50 )
    private String luogonascita;

    @Size( max = 20 )
    private String medicobase;

    @Size( max = 255 )
    private String memocrypto;

    @Size( max = 255 )
    private String memodon;

    @NotNull
    private Integer mesidisponib;

    @Size( max = 255 )
    private String motivocancell;

    @NotNull
    private Short nobenem;

    @NotNull
    private Short nonpresentato;

    @Size( max = 255 )
    private String notaidoneita;

    @Size( max = 10 )
    private String nucleofam;

    @NotNull
    private Integer occupazione;

    @NotNull
    private Short plasmaferesi;

    @NotNull
    private Short plasmapltaferes;

    @NotNull
    private Short pltaferesi;

    @NotNull
    private Short prefdomenica;

    @NotNull
    private Short prefgiovedi;

    @NotNull
    private Short preflunedi;

    @NotNull
    private Short prefmartedi;

    @NotNull
    private Short prefmercoledi;

    @NotNull
    private Short prefsabato;

    @NotNull
    private Short prefvenerdi;

    @NotNull
    private Integer professione;


    private Date prossaferesi;


    private Date prossdonazione;

    @Size( max = 2 )
    private String provdinascita;

    @NotNull
    private Integer ramoattivita;

    @Size( max = 4 )
    private String reperal;

    @Size( max = 4 )
    private String reperdal;

    @Size( max = 5 )
    private String rescap;

    @Size( max = 50 )
    private String rescitta;

    @Size( max = 80 )
    private String resindirizzo;

    @Size( max = 6 )
    private String resistat;

    @Size( max = 40 )
    private String reslocalita;

    @Size( max = 2 )
    private String resprov;

    @Size( max = 20 )
    private String restel;

    @NotNull
    private Integer rh;

    @NotNull
    private Short sangueintero;

    @Size( max = 30 )
    private String sedeprimaiscr;

    @NotNull
    @Size( min = 1, max = 1 )
    private String sesso;

    @NotNull
    private Integer sezione;

    @Size( max = 30 )
    private String solocognome;

    @Size( max = 30 )
    private String solonome;

    @NotNull
    private Short stampadomres;

    @NotNull
    private Integer statoassociat;

    @NotNull
    private Integer statocivile;

    @Size( max = 11 )
    private String tessera;

    @Size( max = 30 )
    private String tesserasanitari;

    @NotNull
    private Short tesserastampata;

    @NotNull
    private Short tesserato;

    @Size( max = 20 )
    private String testolibero1;

    @Size( max = 20 )
    private String testolibero2;

    @NotNull
    private Integer tipodocconvoc;

    @NotNull
    private Integer tipodonazione;

    @Size( max = 10 )
    private String titolo;

    @NotNull
    private Integer titolostudio;

    @NotNull
    private Integer totaleaferesi;

    @NotNull
    private Integer totaledonazioni;

    @NotNull
    private Integer totalesi;


    private Date trasfadata;


    private Date trasfdadata;

    @NotNull
    private Short trasferito;

    @Size( max = 255 )
    private String trasferitoa;

    @Size( max = 255 )
    private String trasferitoda;


    private Date ultimaaferesi;


    private Date ultimdonazione;


    private Date ultimochecku;


    private Date ultimoecg;


    private Date ultimoesacontr;


    private Date ultimorx;


    private Date ultimourine;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCodinternodonat( String codinternodonat ) {
        this.codinternodonat = codinternodonat ;
    }

    public String getCodinternodonat() {
        return this.codinternodonat;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setAb0( Integer ab0 ) {
        this.ab0 = ab0;
    }
    public Integer getAb0() {
        return this.ab0;
    }

    public void setAferesianno( Integer aferesianno ) {
        this.aferesianno = aferesianno;
    }
    public Integer getAferesianno() {
        return this.aferesianno;
    }

    public void setAferesimultipla( Short aferesimultipla ) {
        this.aferesimultipla = aferesimultipla;
    }
    public Short getAferesimultipla() {
        return this.aferesimultipla;
    }

    public void setAferesipregres( Integer aferesipregres ) {
        this.aferesipregres = aferesipregres;
    }
    public Integer getAferesipregres() {
        return this.aferesipregres;
    }

    public void setAllerg2al( String allerg2al ) {
        this.allerg2al = allerg2al;
    }
    public String getAllerg2al() {
        return this.allerg2al;
    }

    public void setAllerg2dal( String allerg2dal ) {
        this.allerg2dal = allerg2dal;
    }
    public String getAllerg2dal() {
        return this.allerg2dal;
    }

    public void setAllergal( String allergal ) {
        this.allergal = allergal;
    }
    public String getAllergal() {
        return this.allergal;
    }

    public void setAllergdal( String allergdal ) {
        this.allergdal = allergdal;
    }
    public String getAllergdal() {
        return this.allergdal;
    }

    public void setAltracarica( String altracarica ) {
        this.altracarica = altracarica;
    }
    public String getAltracarica() {
        return this.altracarica;
    }

    public void setBloccatoda( Integer bloccatoda ) {
        this.bloccatoda = bloccatoda;
    }
    public Integer getBloccatoda() {
        return this.bloccatoda;
    }

    public void setCancelladefin( Date cancelladefin ) {
        this.cancelladefin = cancelladefin;
    }
    public Date getCancelladefin() {
        return this.cancelladefin;
    }

    public void setCapofamiglia( Short capofamiglia ) {
        this.capofamiglia = capofamiglia;
    }
    public Short getCapofamiglia() {
        return this.capofamiglia;
    }

    public void setCaricasociale( Integer caricasociale ) {
        this.caricasociale = caricasociale;
    }
    public Integer getCaricasociale() {
        return this.caricasociale;
    }

    public void setCellulare( String cellulare ) {
        this.cellulare = cellulare;
    }
    public String getCellulare() {
        return this.cellulare;
    }

    public void setCellulestamina( Short cellulestamina ) {
        this.cellulestamina = cellulestamina;
    }
    public Short getCellulestamina() {
        return this.cellulestamina;
    }

    public void setCodcomunenasc( String codcomunenasc ) {
        this.codcomunenasc = codcomunenasc;
    }
    public String getCodcomunenasc() {
        return this.codcomunenasc;
    }

    public void setCodconvocazion( Integer codconvocazion ) {
        this.codconvocazion = codconvocazion;
    }
    public Integer getCodconvocazion() {
        return this.codconvocazion;
    }

    public void setCodicedonatore( String codicedonatore ) {
        this.codicedonatore = codicedonatore;
    }
    public String getCodicedonatore() {
        return this.codicedonatore;
    }

    public void setCodicefiscale( String codicefiscale ) {
        this.codicefiscale = codicefiscale;
    }
    public String getCodicefiscale() {
        return this.codicefiscale;
    }

    public void setCodicelogido( String codicelogido ) {
        this.codicelogido = codicelogido;
    }
    public String getCodicelogido() {
        return this.codicelogido;
    }

    public void setCodicereg( String codicereg ) {
        this.codicereg = codicereg;
    }
    public String getCodicereg() {
        return this.codicereg;
    }

    public void setCognomedasposat( String cognomedasposat ) {
        this.cognomedasposat = cognomedasposat;
    }
    public String getCognomedasposat() {
        return this.cognomedasposat;
    }

    public void setCognomeenome( String cognomeenome ) {
        this.cognomeenome = cognomeenome;
    }
    public String getCognomeenome() {
        return this.cognomeenome;
    }

    public void setCommissione1( Short commissione1 ) {
        this.commissione1 = commissione1;
    }
    public Short getCommissione1() {
        return this.commissione1;
    }

    public void setCommissione2( Short commissione2 ) {
        this.commissione2 = commissione2;
    }
    public Short getCommissione2() {
        return this.commissione2;
    }

    public void setCommissione3( Short commissione3 ) {
        this.commissione3 = commissione3;
    }
    public Short getCommissione3() {
        return this.commissione3;
    }

    public void setCommissione4( Short commissione4 ) {
        this.commissione4 = commissione4;
    }
    public Short getCommissione4() {
        return this.commissione4;
    }

    public void setCommissione5( Short commissione5 ) {
        this.commissione5 = commissione5;
    }
    public Short getCommissione5() {
        return this.commissione5;
    }

    public void setCommissione6( Short commissione6 ) {
        this.commissione6 = commissione6;
    }
    public Short getCommissione6() {
        return this.commissione6;
    }

    public void setCommissione7( Short commissione7 ) {
        this.commissione7 = commissione7;
    }
    public Short getCommissione7() {
        return this.commissione7;
    }

    public void setCommissione8( Short commissione8 ) {
        this.commissione8 = commissione8;
    }
    public Short getCommissione8() {
        return this.commissione8;
    }

    public void setCommissione9( Short commissione9 ) {
        this.commissione9 = commissione9;
    }
    public Short getCommissione9() {
        return this.commissione9;
    }

    public void setConsigplasmaf( Short consigplasmaf ) {
        this.consigplasmaf = consigplasmaf;
    }
    public Short getConsigplasmaf() {
        return this.consigplasmaf;
    }

    public void setConvocato( Short convocato ) {
        this.convocato = convocato;
    }
    public Short getConvocato() {
        return this.convocato;
    }

    public void setDataaltraben( Date dataaltraben ) {
        this.dataaltraben = dataaltraben;
    }
    public Date getDataaltraben() {
        return this.dataaltraben;
    }

    public void setDatabenemerenz( Date databenemerenz ) {
        this.databenemerenz = databenemerenz;
    }
    public Date getDatabenemerenz() {
        return this.databenemerenz;
    }

    public void setDataconvpren( Date dataconvpren ) {
        this.dataconvpren = dataconvpren;
    }
    public Date getDataconvpren() {
        return this.dataconvpren;
    }

    public void setDatacroceoro( Date datacroceoro ) {
        this.datacroceoro = datacroceoro;
    }
    public Date getDatacroceoro() {
        return this.datacroceoro;
    }

    public void setDatadinascita( Date datadinascita ) {
        this.datadinascita = datadinascita;
    }
    public Date getDatadinascita() {
        return this.datadinascita;
    }

    public void setDatadistintivo( Date datadistintivo ) {
        this.datadistintivo = datadistintivo;
    }
    public Date getDatadistintivo() {
        return this.datadistintivo;
    }

    public void setDatafinestato( Date datafinestato ) {
        this.datafinestato = datafinestato;
    }
    public Date getDatafinestato() {
        return this.datafinestato;
    }

    public void setDatagocciaarg( Date datagocciaarg ) {
        this.datagocciaarg = datagocciaarg;
    }
    public Date getDatagocciaarg() {
        return this.datagocciaarg;
    }

    public void setDatagocciabro( Date datagocciabro ) {
        this.datagocciabro = datagocciabro;
    }
    public Date getDatagocciabro() {
        return this.datagocciabro;
    }

    public void setDatagocciaoro( Date datagocciaoro ) {
        this.datagocciaoro = datagocciaoro;
    }
    public Date getDatagocciaoro() {
        return this.datagocciaoro;
    }

    public void setDatainiziostato( Date datainiziostato ) {
        this.datainiziostato = datainiziostato;
    }
    public Date getDatainiziostato() {
        return this.datainiziostato;
    }

    public void setDatamedargent( Date datamedargent ) {
        this.datamedargent = datamedargent;
    }
    public Date getDatamedargent() {
        return this.datamedargent;
    }

    public void setDatamedbronzo( Date datamedbronzo ) {
        this.datamedbronzo = datamedbronzo;
    }
    public Date getDatamedbronzo() {
        return this.datamedbronzo;
    }

    public void setDatamedoro( Date datamedoro ) {
        this.datamedoro = datamedoro;
    }
    public Date getDatamedoro() {
        return this.datamedoro;
    }

    public void setDatanuovaanagrafica( Date datanuovaanagrafica ) {
        this.datanuovaanagrafica = datanuovaanagrafica;
    }
    public Date getDatanuovaanagrafica() {
        return this.datanuovaanagrafica;
    }

    public void setDatapremagg( Date datapremagg ) {
        this.datapremagg = datapremagg;
    }
    public Date getDatapremagg() {
        return this.datapremagg;
    }

    public void setDataprimaiscr( Date dataprimaiscr ) {
        this.dataprimaiscr = dataprimaiscr;
    }
    public Date getDataprimaiscr() {
        return this.dataprimaiscr;
    }

    public void setDatarubinocoll( Date datarubinocoll ) {
        this.datarubinocoll = datarubinocoll;
    }
    public Date getDatarubinocoll() {
        return this.datarubinocoll;
    }

    public void setDettagliososp( String dettagliososp ) {
        this.dettagliososp = dettagliososp;
    }
    public String getDettagliososp() {
        return this.dettagliososp;
    }

    public void setDomcap( String domcap ) {
        this.domcap = domcap;
    }
    public String getDomcap() {
        return this.domcap;
    }

    public void setDomcitta( String domcitta ) {
        this.domcitta = domcitta;
    }
    public String getDomcitta() {
        return this.domcitta;
    }

    public void setDomindirizzo( String domindirizzo ) {
        this.domindirizzo = domindirizzo;
    }
    public String getDomindirizzo() {
        return this.domindirizzo;
    }

    public void setDomistat( String domistat ) {
        this.domistat = domistat;
    }
    public String getDomistat() {
        return this.domistat;
    }

    public void setDomlocalita( String domlocalita ) {
        this.domlocalita = domlocalita;
    }
    public String getDomlocalita() {
        return this.domlocalita;
    }

    public void setDomprov( String domprov ) {
        this.domprov = domprov;
    }
    public String getDomprov() {
        return this.domprov;
    }

    public void setDomresuguali( Short domresuguali ) {
        this.domresuguali = domresuguali;
    }
    public Short getDomresuguali() {
        return this.domresuguali;
    }

    public void setDomtel( String domtel ) {
        this.domtel = domtel;
    }
    public String getDomtel() {
        return this.domtel;
    }

    public void setDonazanno( Integer donazanno ) {
        this.donazanno = donazanno;
    }
    public Integer getDonazanno() {
        return this.donazanno;
    }

    public void setDonazionipregr( Integer donazionipregr ) {
        this.donazionipregr = donazionipregr;
    }
    public Integer getDonazionipregr() {
        return this.donazionipregr;
    }

    public void setDonazionipregrdopo2004( Short donazionipregrdopo2004 ) {
        this.donazionipregrdopo2004 = donazionipregrdopo2004;
    }
    public Short getDonazionipregrdopo2004() {
        return this.donazionipregrdopo2004;
    }

    public void setDoppiapltaf( Short doppiapltaf ) {
        this.doppiapltaf = doppiapltaf;
    }
    public Short getDoppiapltaf() {
        return this.doppiapltaf;
    }

    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    public void setEritroplasma( Short eritroplasma ) {
        this.eritroplasma = eritroplasma;
    }
    public Short getEritroplasma() {
        return this.eritroplasma;
    }

    public void setEritroplt( Short eritroplt ) {
        this.eritroplt = eritroplt;
    }
    public Short getEritroplt() {
        return this.eritroplt;
    }

    public void setFermoposta( String fermoposta ) {
        this.fermoposta = fermoposta;
    }
    public String getFermoposta() {
        return this.fermoposta;
    }

    public void setFlagallergia( Short flagallergia ) {
        this.flagallergia = flagallergia;
    }
    public Short getFlagallergia() {
        return this.flagallergia;
    }

    public void setFlagaltrabene( Short flagaltrabene ) {
        this.flagaltrabene = flagaltrabene;
    }
    public Short getFlagaltrabene() {
        return this.flagaltrabene;
    }

    public void setFlagbenemerenz( Short flagbenemerenz ) {
        this.flagbenemerenz = flagbenemerenz;
    }
    public Short getFlagbenemerenz() {
        return this.flagbenemerenz;
    }

    public void setFlagcroceoro( Short flagcroceoro ) {
        this.flagcroceoro = flagcroceoro;
    }
    public Short getFlagcroceoro() {
        return this.flagcroceoro;
    }

    public void setFlagdistintivo( Short flagdistintivo ) {
        this.flagdistintivo = flagdistintivo;
    }
    public Short getFlagdistintivo() {
        return this.flagdistintivo;
    }

    public void setFlaggocciaarg( Short flaggocciaarg ) {
        this.flaggocciaarg = flaggocciaarg;
    }
    public Short getFlaggocciaarg() {
        return this.flaggocciaarg;
    }

    public void setFlaggocciabro( Short flaggocciabro ) {
        this.flaggocciabro = flaggocciabro;
    }
    public Short getFlaggocciabro() {
        return this.flaggocciabro;
    }

    public void setFlaggocciaoro( Short flaggocciaoro ) {
        this.flaggocciaoro = flaggocciaoro;
    }
    public Short getFlaggocciaoro() {
        return this.flaggocciaoro;
    }

    public void setFlagmail( Short flagmail ) {
        this.flagmail = flagmail;
    }
    public Short getFlagmail() {
        return this.flagmail;
    }

    public void setFlagmedargent( Short flagmedargent ) {
        this.flagmedargent = flagmedargent;
    }
    public Short getFlagmedargent() {
        return this.flagmedargent;
    }

    public void setFlagmedbronzo( Short flagmedbronzo ) {
        this.flagmedbronzo = flagmedbronzo;
    }
    public Short getFlagmedbronzo() {
        return this.flagmedbronzo;
    }

    public void setFlagmedoro( Short flagmedoro ) {
        this.flagmedoro = flagmedoro;
    }
    public Short getFlagmedoro() {
        return this.flagmedoro;
    }

    public void setFlagpremagg( Short flagpremagg ) {
        this.flagpremagg = flagpremagg;
    }
    public Short getFlagpremagg() {
        return this.flagpremagg;
    }

    public void setFlagreperibile( Short flagreperibile ) {
        this.flagreperibile = flagreperibile;
    }
    public Short getFlagreperibile() {
        return this.flagreperibile;
    }

    public void setFlagrubinocoll( Short flagrubinocoll ) {
        this.flagrubinocoll = flagrubinocoll;
    }
    public Short getFlagrubinocoll() {
        return this.flagrubinocoll;
    }

    public void setFlagsms( Short flagsms ) {
        this.flagsms = flagsms;
    }
    public Short getFlagsms() {
        return this.flagsms;
    }

    public void setGruppoorganizz( Integer gruppoorganizz ) {
        this.gruppoorganizz = gruppoorganizz;
    }
    public Integer getGruppoorganizz() {
        return this.gruppoorganizz;
    }

    public void setIdoneita( Integer idoneita ) {
        this.idoneita = idoneita;
    }
    public Integer getIdoneita() {
        return this.idoneita;
    }

    public void setImportato( Short importato ) {
        this.importato = importato;
    }
    public Short getImportato() {
        return this.importato;
    }

    public void setIndicpiastrafer( Short indicpiastrafer ) {
        this.indicpiastrafer = indicpiastrafer;
    }
    public Short getIndicpiastrafer() {
        return this.indicpiastrafer;
    }

    public void setIntervalloafeaf( Integer intervalloafeaf ) {
        this.intervalloafeaf = intervalloafeaf;
    }
    public Integer getIntervalloafeaf() {
        return this.intervalloafeaf;
    }

    public void setIntervalloafesa( Integer intervalloafesa ) {
        this.intervalloafesa = intervalloafesa;
    }
    public Integer getIntervalloafesa() {
        return this.intervalloafesa;
    }

    public void setIntervallosalaf( Integer intervallosalaf ) {
        this.intervallosalaf = intervallosalaf;
    }
    public Integer getIntervallosalaf() {
        return this.intervallosalaf;
    }

    public void setIntervallosalsa( Integer intervallosalsa ) {
        this.intervallosalsa = intervallosalsa;
    }
    public Integer getIntervallosalsa() {
        return this.intervallosalsa;
    }

    public void setIscradmo( Short iscradmo ) {
        this.iscradmo = iscradmo;
    }
    public Short getIscradmo() {
        return this.iscradmo;
    }

    public void setIscraido( Short iscraido ) {
        this.iscraido = iscraido;
    }
    public Short getIscraido() {
        return this.iscraido;
    }

    public void setKell( Integer kell ) {
        this.kell = kell;
    }
    public Integer getKell() {
        return this.kell;
    }

    public void setLavcodice( String lavcodice ) {
        this.lavcodice = lavcodice;
    }
    public String getLavcodice() {
        return this.lavcodice;
    }

    public void setLavtel( String lavtel ) {
        this.lavtel = lavtel;
    }
    public String getLavtel() {
        return this.lavtel;
    }

    public void setLeggeprivacy( Short leggeprivacy ) {
        this.leggeprivacy = leggeprivacy;
    }
    public Short getLeggeprivacy() {
        return this.leggeprivacy;
    }

    public void setLettprimadonstampata( Short lettprimadonstampata ) {
        this.lettprimadonstampata = lettprimadonstampata;
    }
    public Short getLettprimadonstampata() {
        return this.lettprimadonstampata;
    }

    public void setLeucoaferesi( Short leucoaferesi ) {
        this.leucoaferesi = leucoaferesi;
    }
    public Short getLeucoaferesi() {
        return this.leucoaferesi;
    }

    public void setLibero0( Short libero0 ) {
        this.libero0 = libero0;
    }
    public Short getLibero0() {
        return this.libero0;
    }

    public void setLibero1( Short libero1 ) {
        this.libero1 = libero1;
    }
    public Short getLibero1() {
        return this.libero1;
    }

    public void setLibero10( Short libero10 ) {
        this.libero10 = libero10;
    }
    public Short getLibero10() {
        return this.libero10;
    }

    public void setLibero11( Short libero11 ) {
        this.libero11 = libero11;
    }
    public Short getLibero11() {
        return this.libero11;
    }

    public void setLibero2( Short libero2 ) {
        this.libero2 = libero2;
    }
    public Short getLibero2() {
        return this.libero2;
    }

    public void setLibero3( Short libero3 ) {
        this.libero3 = libero3;
    }
    public Short getLibero3() {
        return this.libero3;
    }

    public void setLibero4( Short libero4 ) {
        this.libero4 = libero4;
    }
    public Short getLibero4() {
        return this.libero4;
    }

    public void setLibero5( Short libero5 ) {
        this.libero5 = libero5;
    }
    public Short getLibero5() {
        return this.libero5;
    }

    public void setLibero6( Short libero6 ) {
        this.libero6 = libero6;
    }
    public Short getLibero6() {
        return this.libero6;
    }

    public void setLibero7( Short libero7 ) {
        this.libero7 = libero7;
    }
    public Short getLibero7() {
        return this.libero7;
    }

    public void setLibero8( Short libero8 ) {
        this.libero8 = libero8;
    }
    public Short getLibero8() {
        return this.libero8;
    }

    public void setLibero9( Short libero9 ) {
        this.libero9 = libero9;
    }
    public Short getLibero9() {
        return this.libero9;
    }

    public void setLuogonascita( String luogonascita ) {
        this.luogonascita = luogonascita;
    }
    public String getLuogonascita() {
        return this.luogonascita;
    }

    public void setMedicobase( String medicobase ) {
        this.medicobase = medicobase;
    }
    public String getMedicobase() {
        return this.medicobase;
    }

    public void setMemocrypto( String memocrypto ) {
        this.memocrypto = memocrypto;
    }
    public String getMemocrypto() {
        return this.memocrypto;
    }

    public void setMemodon( String memodon ) {
        this.memodon = memodon;
    }
    public String getMemodon() {
        return this.memodon;
    }

    public void setMesidisponib( Integer mesidisponib ) {
        this.mesidisponib = mesidisponib;
    }
    public Integer getMesidisponib() {
        return this.mesidisponib;
    }

    public void setMotivocancell( String motivocancell ) {
        this.motivocancell = motivocancell;
    }
    public String getMotivocancell() {
        return this.motivocancell;
    }

    public void setNobenem( Short nobenem ) {
        this.nobenem = nobenem;
    }
    public Short getNobenem() {
        return this.nobenem;
    }

    public void setNonpresentato( Short nonpresentato ) {
        this.nonpresentato = nonpresentato;
    }
    public Short getNonpresentato() {
        return this.nonpresentato;
    }

    public void setNotaidoneita( String notaidoneita ) {
        this.notaidoneita = notaidoneita;
    }
    public String getNotaidoneita() {
        return this.notaidoneita;
    }

    public void setNucleofam( String nucleofam ) {
        this.nucleofam = nucleofam;
    }
    public String getNucleofam() {
        return this.nucleofam;
    }

    public void setOccupazione( Integer occupazione ) {
        this.occupazione = occupazione;
    }
    public Integer getOccupazione() {
        return this.occupazione;
    }

    public void setPlasmaferesi( Short plasmaferesi ) {
        this.plasmaferesi = plasmaferesi;
    }
    public Short getPlasmaferesi() {
        return this.plasmaferesi;
    }

    public void setPlasmapltaferes( Short plasmapltaferes ) {
        this.plasmapltaferes = plasmapltaferes;
    }
    public Short getPlasmapltaferes() {
        return this.plasmapltaferes;
    }

    public void setPltaferesi( Short pltaferesi ) {
        this.pltaferesi = pltaferesi;
    }
    public Short getPltaferesi() {
        return this.pltaferesi;
    }

    public void setPrefdomenica( Short prefdomenica ) {
        this.prefdomenica = prefdomenica;
    }
    public Short getPrefdomenica() {
        return this.prefdomenica;
    }

    public void setPrefgiovedi( Short prefgiovedi ) {
        this.prefgiovedi = prefgiovedi;
    }
    public Short getPrefgiovedi() {
        return this.prefgiovedi;
    }

    public void setPreflunedi( Short preflunedi ) {
        this.preflunedi = preflunedi;
    }
    public Short getPreflunedi() {
        return this.preflunedi;
    }

    public void setPrefmartedi( Short prefmartedi ) {
        this.prefmartedi = prefmartedi;
    }
    public Short getPrefmartedi() {
        return this.prefmartedi;
    }

    public void setPrefmercoledi( Short prefmercoledi ) {
        this.prefmercoledi = prefmercoledi;
    }
    public Short getPrefmercoledi() {
        return this.prefmercoledi;
    }

    public void setPrefsabato( Short prefsabato ) {
        this.prefsabato = prefsabato;
    }
    public Short getPrefsabato() {
        return this.prefsabato;
    }

    public void setPrefvenerdi( Short prefvenerdi ) {
        this.prefvenerdi = prefvenerdi;
    }
    public Short getPrefvenerdi() {
        return this.prefvenerdi;
    }

    public void setProfessione( Integer professione ) {
        this.professione = professione;
    }
    public Integer getProfessione() {
        return this.professione;
    }

    public void setProssaferesi( Date prossaferesi ) {
        this.prossaferesi = prossaferesi;
    }
    public Date getProssaferesi() {
        return this.prossaferesi;
    }

    public void setProssdonazione( Date prossdonazione ) {
        this.prossdonazione = prossdonazione;
    }
    public Date getProssdonazione() {
        return this.prossdonazione;
    }

    public void setProvdinascita( String provdinascita ) {
        this.provdinascita = provdinascita;
    }
    public String getProvdinascita() {
        return this.provdinascita;
    }

    public void setRamoattivita( Integer ramoattivita ) {
        this.ramoattivita = ramoattivita;
    }
    public Integer getRamoattivita() {
        return this.ramoattivita;
    }

    public void setReperal( String reperal ) {
        this.reperal = reperal;
    }
    public String getReperal() {
        return this.reperal;
    }

    public void setReperdal( String reperdal ) {
        this.reperdal = reperdal;
    }
    public String getReperdal() {
        return this.reperdal;
    }

    public void setRescap( String rescap ) {
        this.rescap = rescap;
    }
    public String getRescap() {
        return this.rescap;
    }

    public void setRescitta( String rescitta ) {
        this.rescitta = rescitta;
    }
    public String getRescitta() {
        return this.rescitta;
    }

    public void setResindirizzo( String resindirizzo ) {
        this.resindirizzo = resindirizzo;
    }
    public String getResindirizzo() {
        return this.resindirizzo;
    }

    public void setResistat( String resistat ) {
        this.resistat = resistat;
    }
    public String getResistat() {
        return this.resistat;
    }

    public void setReslocalita( String reslocalita ) {
        this.reslocalita = reslocalita;
    }
    public String getReslocalita() {
        return this.reslocalita;
    }

    public void setResprov( String resprov ) {
        this.resprov = resprov;
    }
    public String getResprov() {
        return this.resprov;
    }

    public void setRestel( String restel ) {
        this.restel = restel;
    }
    public String getRestel() {
        return this.restel;
    }

    public void setRh( Integer rh ) {
        this.rh = rh;
    }
    public Integer getRh() {
        return this.rh;
    }

    public void setSangueintero( Short sangueintero ) {
        this.sangueintero = sangueintero;
    }
    public Short getSangueintero() {
        return this.sangueintero;
    }

    public void setSedeprimaiscr( String sedeprimaiscr ) {
        this.sedeprimaiscr = sedeprimaiscr;
    }
    public String getSedeprimaiscr() {
        return this.sedeprimaiscr;
    }

    public void setSesso( String sesso ) {
        this.sesso = sesso;
    }
    public String getSesso() {
        return this.sesso;
    }

    public void setSezione( Integer sezione ) {
        this.sezione = sezione;
    }
    public Integer getSezione() {
        return this.sezione;
    }

    public void setSolocognome( String solocognome ) {
        this.solocognome = solocognome;
    }
    public String getSolocognome() {
        return this.solocognome;
    }

    public void setSolonome( String solonome ) {
        this.solonome = solonome;
    }
    public String getSolonome() {
        return this.solonome;
    }

    public void setStampadomres( Short stampadomres ) {
        this.stampadomres = stampadomres;
    }
    public Short getStampadomres() {
        return this.stampadomres;
    }

    public void setStatoassociat( Integer statoassociat ) {
        this.statoassociat = statoassociat;
    }
    public Integer getStatoassociat() {
        return this.statoassociat;
    }

    public void setStatocivile( Integer statocivile ) {
        this.statocivile = statocivile;
    }
    public Integer getStatocivile() {
        return this.statocivile;
    }

    public void setTessera( String tessera ) {
        this.tessera = tessera;
    }
    public String getTessera() {
        return this.tessera;
    }

    public void setTesserasanitari( String tesserasanitari ) {
        this.tesserasanitari = tesserasanitari;
    }
    public String getTesserasanitari() {
        return this.tesserasanitari;
    }

    public void setTesserastampata( Short tesserastampata ) {
        this.tesserastampata = tesserastampata;
    }
    public Short getTesserastampata() {
        return this.tesserastampata;
    }

    public void setTesserato( Short tesserato ) {
        this.tesserato = tesserato;
    }
    public Short getTesserato() {
        return this.tesserato;
    }

    public void setTestolibero1( String testolibero1 ) {
        this.testolibero1 = testolibero1;
    }
    public String getTestolibero1() {
        return this.testolibero1;
    }

    public void setTestolibero2( String testolibero2 ) {
        this.testolibero2 = testolibero2;
    }
    public String getTestolibero2() {
        return this.testolibero2;
    }

    public void setTipodocconvoc( Integer tipodocconvoc ) {
        this.tipodocconvoc = tipodocconvoc;
    }
    public Integer getTipodocconvoc() {
        return this.tipodocconvoc;
    }

    public void setTipodonazione( Integer tipodonazione ) {
        this.tipodonazione = tipodonazione;
    }
    public Integer getTipodonazione() {
        return this.tipodonazione;
    }

    public void setTitolo( String titolo ) {
        this.titolo = titolo;
    }
    public String getTitolo() {
        return this.titolo;
    }

    public void setTitolostudio( Integer titolostudio ) {
        this.titolostudio = titolostudio;
    }
    public Integer getTitolostudio() {
        return this.titolostudio;
    }

    public void setTotaleaferesi( Integer totaleaferesi ) {
        this.totaleaferesi = totaleaferesi;
    }
    public Integer getTotaleaferesi() {
        return this.totaleaferesi;
    }

    public void setTotaledonazioni( Integer totaledonazioni ) {
        this.totaledonazioni = totaledonazioni;
    }
    public Integer getTotaledonazioni() {
        return this.totaledonazioni;
    }

    public void setTotalesi( Integer totalesi ) {
        this.totalesi = totalesi;
    }
    public Integer getTotalesi() {
        return this.totalesi;
    }

    public void setTrasfadata( Date trasfadata ) {
        this.trasfadata = trasfadata;
    }
    public Date getTrasfadata() {
        return this.trasfadata;
    }

    public void setTrasfdadata( Date trasfdadata ) {
        this.trasfdadata = trasfdadata;
    }
    public Date getTrasfdadata() {
        return this.trasfdadata;
    }

    public void setTrasferito( Short trasferito ) {
        this.trasferito = trasferito;
    }
    public Short getTrasferito() {
        return this.trasferito;
    }

    public void setTrasferitoa( String trasferitoa ) {
        this.trasferitoa = trasferitoa;
    }
    public String getTrasferitoa() {
        return this.trasferitoa;
    }

    public void setTrasferitoda( String trasferitoda ) {
        this.trasferitoda = trasferitoda;
    }
    public String getTrasferitoda() {
        return this.trasferitoda;
    }

    public void setUltimaaferesi( Date ultimaaferesi ) {
        this.ultimaaferesi = ultimaaferesi;
    }
    public Date getUltimaaferesi() {
        return this.ultimaaferesi;
    }

    public void setUltimdonazione( Date ultimdonazione ) {
        this.ultimdonazione = ultimdonazione;
    }
    public Date getUltimdonazione() {
        return this.ultimdonazione;
    }

    public void setUltimochecku( Date ultimochecku ) {
        this.ultimochecku = ultimochecku;
    }
    public Date getUltimochecku() {
        return this.ultimochecku;
    }

    public void setUltimoecg( Date ultimoecg ) {
        this.ultimoecg = ultimoecg;
    }
    public Date getUltimoecg() {
        return this.ultimoecg;
    }

    public void setUltimoesacontr( Date ultimoesacontr ) {
        this.ultimoesacontr = ultimoesacontr;
    }
    public Date getUltimoesacontr() {
        return this.ultimoesacontr;
    }

    public void setUltimorx( Date ultimorx ) {
        this.ultimorx = ultimorx;
    }
    public Date getUltimorx() {
        return this.ultimorx;
    }

    public void setUltimourine( Date ultimourine ) {
        this.ultimourine = ultimourine;
    }
    public Date getUltimourine() {
        return this.ultimourine;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(codinternodonat);
        sb.append("|");
        sb.append(ab0);
        sb.append("|");
        sb.append(aferesianno);
        sb.append("|");
        sb.append(aferesimultipla);
        sb.append("|");
        sb.append(aferesipregres);
        sb.append("|");
        sb.append(allerg2al);
        sb.append("|");
        sb.append(allerg2dal);
        sb.append("|");
        sb.append(allergal);
        sb.append("|");
        sb.append(allergdal);
        sb.append("|");
        sb.append(altracarica);
        sb.append("|");
        sb.append(bloccatoda);
        sb.append("|");
        sb.append(cancelladefin);
        sb.append("|");
        sb.append(capofamiglia);
        sb.append("|");
        sb.append(caricasociale);
        sb.append("|");
        sb.append(cellulare);
        sb.append("|");
        sb.append(cellulestamina);
        sb.append("|");
        sb.append(codcomunenasc);
        sb.append("|");
        sb.append(codconvocazion);
        sb.append("|");
        sb.append(codicedonatore);
        sb.append("|");
        sb.append(codicefiscale);
        sb.append("|");
        sb.append(codicelogido);
        sb.append("|");
        sb.append(codicereg);
        sb.append("|");
        sb.append(cognomedasposat);
        sb.append("|");
        sb.append(cognomeenome);
        sb.append("|");
        sb.append(commissione1);
        sb.append("|");
        sb.append(commissione2);
        sb.append("|");
        sb.append(commissione3);
        sb.append("|");
        sb.append(commissione4);
        sb.append("|");
        sb.append(commissione5);
        sb.append("|");
        sb.append(commissione6);
        sb.append("|");
        sb.append(commissione7);
        sb.append("|");
        sb.append(commissione8);
        sb.append("|");
        sb.append(commissione9);
        sb.append("|");
        sb.append(consigplasmaf);
        sb.append("|");
        sb.append(convocato);
        sb.append("|");
        sb.append(dataaltraben);
        sb.append("|");
        sb.append(databenemerenz);
        sb.append("|");
        sb.append(dataconvpren);
        sb.append("|");
        sb.append(datacroceoro);
        sb.append("|");
        sb.append(datadinascita);
        sb.append("|");
        sb.append(datadistintivo);
        sb.append("|");
        sb.append(datafinestato);
        sb.append("|");
        sb.append(datagocciaarg);
        sb.append("|");
        sb.append(datagocciabro);
        sb.append("|");
        sb.append(datagocciaoro);
        sb.append("|");
        sb.append(datainiziostato);
        sb.append("|");
        sb.append(datamedargent);
        sb.append("|");
        sb.append(datamedbronzo);
        sb.append("|");
        sb.append(datamedoro);
        sb.append("|");
        sb.append(datanuovaanagrafica);
        sb.append("|");
        sb.append(datapremagg);
        sb.append("|");
        sb.append(dataprimaiscr);
        sb.append("|");
        sb.append(datarubinocoll);
        sb.append("|");
        sb.append(dettagliososp);
        sb.append("|");
        sb.append(domcap);
        sb.append("|");
        sb.append(domcitta);
        sb.append("|");
        sb.append(domindirizzo);
        sb.append("|");
        sb.append(domistat);
        sb.append("|");
        sb.append(domlocalita);
        sb.append("|");
        sb.append(domprov);
        sb.append("|");
        sb.append(domresuguali);
        sb.append("|");
        sb.append(domtel);
        sb.append("|");
        sb.append(donazanno);
        sb.append("|");
        sb.append(donazionipregr);
        sb.append("|");
        sb.append(donazionipregrdopo2004);
        sb.append("|");
        sb.append(doppiapltaf);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(eritroplasma);
        sb.append("|");
        sb.append(eritroplt);
        sb.append("|");
        sb.append(fermoposta);
        sb.append("|");
        sb.append(flagallergia);
        sb.append("|");
        sb.append(flagaltrabene);
        sb.append("|");
        sb.append(flagbenemerenz);
        sb.append("|");
        sb.append(flagcroceoro);
        sb.append("|");
        sb.append(flagdistintivo);
        sb.append("|");
        sb.append(flaggocciaarg);
        sb.append("|");
        sb.append(flaggocciabro);
        sb.append("|");
        sb.append(flaggocciaoro);
        sb.append("|");
        sb.append(flagmail);
        sb.append("|");
        sb.append(flagmedargent);
        sb.append("|");
        sb.append(flagmedbronzo);
        sb.append("|");
        sb.append(flagmedoro);
        sb.append("|");
        sb.append(flagpremagg);
        sb.append("|");
        sb.append(flagreperibile);
        sb.append("|");
        sb.append(flagrubinocoll);
        sb.append("|");
        sb.append(flagsms);
        sb.append("|");
        sb.append(gruppoorganizz);
        sb.append("|");
        sb.append(idoneita);
        sb.append("|");
        sb.append(importato);
        sb.append("|");
        sb.append(indicpiastrafer);
        sb.append("|");
        sb.append(intervalloafeaf);
        sb.append("|");
        sb.append(intervalloafesa);
        sb.append("|");
        sb.append(intervallosalaf);
        sb.append("|");
        sb.append(intervallosalsa);
        sb.append("|");
        sb.append(iscradmo);
        sb.append("|");
        sb.append(iscraido);
        sb.append("|");
        sb.append(kell);
        sb.append("|");
        sb.append(lavcodice);
        sb.append("|");
        sb.append(lavtel);
        sb.append("|");
        sb.append(leggeprivacy);
        sb.append("|");
        sb.append(lettprimadonstampata);
        sb.append("|");
        sb.append(leucoaferesi);
        sb.append("|");
        sb.append(libero0);
        sb.append("|");
        sb.append(libero1);
        sb.append("|");
        sb.append(libero10);
        sb.append("|");
        sb.append(libero11);
        sb.append("|");
        sb.append(libero2);
        sb.append("|");
        sb.append(libero3);
        sb.append("|");
        sb.append(libero4);
        sb.append("|");
        sb.append(libero5);
        sb.append("|");
        sb.append(libero6);
        sb.append("|");
        sb.append(libero7);
        sb.append("|");
        sb.append(libero8);
        sb.append("|");
        sb.append(libero9);
        sb.append("|");
        sb.append(luogonascita);
        sb.append("|");
        sb.append(medicobase);
        sb.append("|");
        sb.append(memocrypto);
        sb.append("|");
        sb.append(memodon);
        sb.append("|");
        sb.append(mesidisponib);
        sb.append("|");
        sb.append(motivocancell);
        sb.append("|");
        sb.append(nobenem);
        sb.append("|");
        sb.append(nonpresentato);
        sb.append("|");
        sb.append(notaidoneita);
        sb.append("|");
        sb.append(nucleofam);
        sb.append("|");
        sb.append(occupazione);
        sb.append("|");
        sb.append(plasmaferesi);
        sb.append("|");
        sb.append(plasmapltaferes);
        sb.append("|");
        sb.append(pltaferesi);
        sb.append("|");
        sb.append(prefdomenica);
        sb.append("|");
        sb.append(prefgiovedi);
        sb.append("|");
        sb.append(preflunedi);
        sb.append("|");
        sb.append(prefmartedi);
        sb.append("|");
        sb.append(prefmercoledi);
        sb.append("|");
        sb.append(prefsabato);
        sb.append("|");
        sb.append(prefvenerdi);
        sb.append("|");
        sb.append(professione);
        sb.append("|");
        sb.append(prossaferesi);
        sb.append("|");
        sb.append(prossdonazione);
        sb.append("|");
        sb.append(provdinascita);
        sb.append("|");
        sb.append(ramoattivita);
        sb.append("|");
        sb.append(reperal);
        sb.append("|");
        sb.append(reperdal);
        sb.append("|");
        sb.append(rescap);
        sb.append("|");
        sb.append(rescitta);
        sb.append("|");
        sb.append(resindirizzo);
        sb.append("|");
        sb.append(resistat);
        sb.append("|");
        sb.append(reslocalita);
        sb.append("|");
        sb.append(resprov);
        sb.append("|");
        sb.append(restel);
        sb.append("|");
        sb.append(rh);
        sb.append("|");
        sb.append(sangueintero);
        sb.append("|");
        sb.append(sedeprimaiscr);
        sb.append("|");
        sb.append(sesso);
        sb.append("|");
        sb.append(sezione);
        sb.append("|");
        sb.append(solocognome);
        sb.append("|");
        sb.append(solonome);
        sb.append("|");
        sb.append(stampadomres);
        sb.append("|");
        sb.append(statoassociat);
        sb.append("|");
        sb.append(statocivile);
        sb.append("|");
        sb.append(tessera);
        sb.append("|");
        sb.append(tesserasanitari);
        sb.append("|");
        sb.append(tesserastampata);
        sb.append("|");
        sb.append(tesserato);
        sb.append("|");
        sb.append(testolibero1);
        sb.append("|");
        sb.append(testolibero2);
        sb.append("|");
        sb.append(tipodocconvoc);
        sb.append("|");
        sb.append(tipodonazione);
        sb.append("|");
        sb.append(titolo);
        sb.append("|");
        sb.append(titolostudio);
        sb.append("|");
        sb.append(totaleaferesi);
        sb.append("|");
        sb.append(totaledonazioni);
        sb.append("|");
        sb.append(totalesi);
        sb.append("|");
        sb.append(trasfadata);
        sb.append("|");
        sb.append(trasfdadata);
        sb.append("|");
        sb.append(trasferito);
        sb.append("|");
        sb.append(trasferitoa);
        sb.append("|");
        sb.append(trasferitoda);
        sb.append("|");
        sb.append(ultimaaferesi);
        sb.append("|");
        sb.append(ultimdonazione);
        sb.append("|");
        sb.append(ultimochecku);
        sb.append("|");
        sb.append(ultimoecg);
        sb.append("|");
        sb.append(ultimoesacontr);
        sb.append("|");
        sb.append(ultimorx);
        sb.append("|");
        sb.append(ultimourine);
        return sb.toString(); 
    } 


}
