/*
 * Created on 21 giu 2016 ( Time 11:51:51 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package it.mesis.avis.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Logidoneita implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 10 )
    private String codicelog;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Short generale;

    @Size( max = 10 )
    private String codinternodonat;


    private Integer idoneita;

    @Size( max = 20 )
    private String motivosospensione;


    private Date dalladata;


    private Date alladata;

    @Size( max = 65535 )
    private String notaidoneita;


    private Short emoc01;


    private Short emoc02;


    private Short emoc03;


    private Short emoc04;


    private Short emoc05;


    private Short emoc06;


    private Short emoc07;


    private Short emoc08;


    private Short emoc09;


    private Short emoc10;


    private Short chiusa;


    private Short letterastampata;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCodicelog( String codicelog ) {
        this.codicelog = codicelog ;
    }

    public String getCodicelog() {
        return this.codicelog;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setGenerale( Short generale ) {
        this.generale = generale;
    }
    public Short getGenerale() {
        return this.generale;
    }

    public void setCodinternodonat( String codinternodonat ) {
        this.codinternodonat = codinternodonat;
    }
    public String getCodinternodonat() {
        return this.codinternodonat;
    }

    public void setIdoneita( Integer idoneita ) {
        this.idoneita = idoneita;
    }
    public Integer getIdoneita() {
        return this.idoneita;
    }

    public void setMotivosospensione( String motivosospensione ) {
        this.motivosospensione = motivosospensione;
    }
    public String getMotivosospensione() {
        return this.motivosospensione;
    }

    public void setDalladata( Date dalladata ) {
        this.dalladata = dalladata;
    }
    public Date getDalladata() {
        return this.dalladata;
    }

    public void setAlladata( Date alladata ) {
        this.alladata = alladata;
    }
    public Date getAlladata() {
        return this.alladata;
    }

    public void setNotaidoneita( String notaidoneita ) {
        this.notaidoneita = notaidoneita;
    }
    public String getNotaidoneita() {
        return this.notaidoneita;
    }

    public void setEmoc01( Short emoc01 ) {
        this.emoc01 = emoc01;
    }
    public Short getEmoc01() {
        return this.emoc01;
    }

    public void setEmoc02( Short emoc02 ) {
        this.emoc02 = emoc02;
    }
    public Short getEmoc02() {
        return this.emoc02;
    }

    public void setEmoc03( Short emoc03 ) {
        this.emoc03 = emoc03;
    }
    public Short getEmoc03() {
        return this.emoc03;
    }

    public void setEmoc04( Short emoc04 ) {
        this.emoc04 = emoc04;
    }
    public Short getEmoc04() {
        return this.emoc04;
    }

    public void setEmoc05( Short emoc05 ) {
        this.emoc05 = emoc05;
    }
    public Short getEmoc05() {
        return this.emoc05;
    }

    public void setEmoc06( Short emoc06 ) {
        this.emoc06 = emoc06;
    }
    public Short getEmoc06() {
        return this.emoc06;
    }

    public void setEmoc07( Short emoc07 ) {
        this.emoc07 = emoc07;
    }
    public Short getEmoc07() {
        return this.emoc07;
    }

    public void setEmoc08( Short emoc08 ) {
        this.emoc08 = emoc08;
    }
    public Short getEmoc08() {
        return this.emoc08;
    }

    public void setEmoc09( Short emoc09 ) {
        this.emoc09 = emoc09;
    }
    public Short getEmoc09() {
        return this.emoc09;
    }

    public void setEmoc10( Short emoc10 ) {
        this.emoc10 = emoc10;
    }
    public Short getEmoc10() {
        return this.emoc10;
    }

    public void setChiusa( Short chiusa ) {
        this.chiusa = chiusa;
    }
    public Short getChiusa() {
        return this.chiusa;
    }

    public void setLetterastampata( Short letterastampata ) {
        this.letterastampata = letterastampata;
    }
    public Short getLetterastampata() {
        return this.letterastampata;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(codicelog);
        sb.append("|");
        sb.append(generale);
        sb.append("|");
        sb.append(codinternodonat);
        sb.append("|");
        sb.append(idoneita);
        sb.append("|");
        sb.append(motivosospensione);
        sb.append("|");
        sb.append(dalladata);
        sb.append("|");
        sb.append(alladata);
        // attribute 'notaidoneita' not usable (type = String Long Text)
        sb.append("|");
        sb.append(emoc01);
        sb.append("|");
        sb.append(emoc02);
        sb.append("|");
        sb.append(emoc03);
        sb.append("|");
        sb.append(emoc04);
        sb.append("|");
        sb.append(emoc05);
        sb.append("|");
        sb.append(emoc06);
        sb.append("|");
        sb.append(emoc07);
        sb.append("|");
        sb.append(emoc08);
        sb.append("|");
        sb.append(emoc09);
        sb.append("|");
        sb.append(emoc10);
        sb.append("|");
        sb.append(chiusa);
        sb.append("|");
        sb.append(letterastampata);
        return sb.toString(); 
    } 


}
