/*
 * Created on 21 giu 2016 ( Time 11:51:51 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package it.mesis.avis.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Macchine implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String disponibilita;

    @Size( max = 20 )
    private String nome;

    @Size( max = 255 )
    private String notamacchina;

    @NotNull
    private Integer pp;

    @NotNull
    private Integer tipodonazId;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDisponibilita( String disponibilita ) {
        this.disponibilita = disponibilita;
    }
    public String getDisponibilita() {
        return this.disponibilita;
    }

    public void setNome( String nome ) {
        this.nome = nome;
    }
    public String getNome() {
        return this.nome;
    }

    public void setNotamacchina( String notamacchina ) {
        this.notamacchina = notamacchina;
    }
    public String getNotamacchina() {
        return this.notamacchina;
    }

    public void setPp( Integer pp ) {
        this.pp = pp;
    }
    public Integer getPp() {
        return this.pp;
    }

    public void setTipodonazId( Integer tipodonazId ) {
        this.tipodonazId = tipodonazId;
    }
    public Integer getTipodonazId() {
        return this.tipodonazId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(disponibilita);
        sb.append("|");
        sb.append(nome);
        sb.append("|");
        sb.append(notamacchina);
        sb.append("|");
        sb.append(pp);
        sb.append("|");
        sb.append(tipodonazId);
        return sb.toString(); 
    } 


}
