/*
 * Created on 21 giu 2016 ( Time 11:50:55 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package it.mesis.avis.service.mapping;

import it.mesis.avis.bean.Audit;
import it.mesis.avis.bean.jpa.AuditEntity;

import java.util.List;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Service;


/**
 * Mapping between entity beans and display beans.
 */
@Service("auditServiceMapper")
public class AuditServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public AuditServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'AuditEntity' to 'Audit'
	 * @param auditEntity
	 */
	public Audit mapAuditEntityToAudit(AuditEntity auditEntity) {
		if(auditEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Audit audit = map(auditEntity, Audit.class);

		return audit;
	}
	
	/**
	 * Mapping from 'AuditEntity list' to 'Audit list'
	 * @param audits
	 * @return
	 */
	public List<Audit> mapAuditEntityToAudit(List<AuditEntity> auditEntity) {
		if(auditEntity == null) {
			return null;
		}
		
		List<Audit> dtos = map(auditEntity, Audit.class);
		
//		List<AuditDto> dtos = new ArrayList<AuditDto>(auditEntity.size());
//		for (AuditEntity audit: auditEntity) {
//			dtos.add(mapAuditEntityToAudit(audit));
//		}
		return dtos;
	}	
	
	/**
	 * Mapping from 'Audit' to 'AuditEntity'
	 * @param audit
	 * @param auditEntity
	 */
	public void mapAuditToAuditEntity(Audit audit, AuditEntity auditEntity) {
		if(audit == null) {
			return;
		}
		//--- Generic mapping 
		map(audit, auditEntity);
	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}