/*
 * Created on 21 giu 2016 ( Time 11:50:56 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package it.mesis.avis.service.mapping;

import it.mesis.avis.bean.Tipodonaz;
import it.mesis.avis.bean.jpa.TipodonazEntity;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Service;

/**
 * Mapping between entity beans and display beans.
 */
@Service
public class TipodonazServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TipodonazServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TipodonazEntity' to 'Tipodonaz'
	 * @param tipodonazEntity
	 */
	public Tipodonaz mapTipodonazEntityToTipodonaz(TipodonazEntity tipodonazEntity) {
		if(tipodonazEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Tipodonaz tipodonaz = map(tipodonazEntity, Tipodonaz.class);

		return tipodonaz;
	}
	
	/**
	 * Mapping from 'Tipodonaz' to 'TipodonazEntity'
	 * @param tipodonaz
	 * @param tipodonazEntity
	 */
	public void mapTipodonazToTipodonazEntity(TipodonazEntity tipodonaz, TipodonazEntity tipodonazEntity) {
		if(tipodonaz == null) {
			return;
		}

		//--- Generic mapping 
		map(tipodonaz, tipodonazEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}